// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOL_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PROTOCOL_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace Protocol {

struct Vec3;

struct C_Move;
struct C_MoveBuilder;

struct S_Move;
struct S_MoveBuilder;

struct Packet;
struct PacketBuilder;

enum PacketData : uint8_t {
  PacketData_NONE = 0,
  PacketData_C_Move = 1,
  PacketData_S_Move = 2,
  PacketData_MIN = PacketData_NONE,
  PacketData_MAX = PacketData_S_Move
};

inline const PacketData (&EnumValuesPacketData())[3] {
  static const PacketData values[] = {
    PacketData_NONE,
    PacketData_C_Move,
    PacketData_S_Move
  };
  return values;
}

inline const char * const *EnumNamesPacketData() {
  static const char * const names[4] = {
    "NONE",
    "C_Move",
    "S_Move",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketData(PacketData e) {
  if (::flatbuffers::IsOutRange(e, PacketData_NONE, PacketData_S_Move)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPacketData()[index];
}

template<typename T> struct PacketDataTraits {
  static const PacketData enum_value = PacketData_NONE;
};

template<> struct PacketDataTraits<Protocol::C_Move> {
  static const PacketData enum_value = PacketData_C_Move;
};

template<> struct PacketDataTraits<Protocol::S_Move> {
  static const PacketData enum_value = PacketData_S_Move;
};

bool VerifyPacketData(::flatbuffers::Verifier &verifier, const void *obj, PacketData type);
bool VerifyPacketDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct C_Move FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C_MoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4
  };
  const Protocol::Vec3 *pos() const {
    return GetStruct<const Protocol::Vec3 *>(VT_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Protocol::Vec3>(verifier, VT_POS, 4) &&
           verifier.EndTable();
  }
};

struct C_MoveBuilder {
  typedef C_Move Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(const Protocol::Vec3 *pos) {
    fbb_.AddStruct(C_Move::VT_POS, pos);
  }
  explicit C_MoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C_Move> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C_Move>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C_Move> CreateC_Move(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Protocol::Vec3 *pos = nullptr) {
  C_MoveBuilder builder_(_fbb);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct S_Move FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S_MoveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_POS = 6
  };
  int32_t player_id() const {
    return GetField<int32_t>(VT_PLAYER_ID, 0);
  }
  const Protocol::Vec3 *pos() const {
    return GetStruct<const Protocol::Vec3 *>(VT_POS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<Protocol::Vec3>(verifier, VT_POS, 4) &&
           verifier.EndTable();
  }
};

struct S_MoveBuilder {
  typedef S_Move Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(int32_t player_id) {
    fbb_.AddElement<int32_t>(S_Move::VT_PLAYER_ID, player_id, 0);
  }
  void add_pos(const Protocol::Vec3 *pos) {
    fbb_.AddStruct(S_Move::VT_POS, pos);
  }
  explicit S_MoveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S_Move> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S_Move>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S_Move> CreateS_Move(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t player_id = 0,
    const Protocol::Vec3 *pos = nullptr) {
  S_MoveBuilder builder_(_fbb);
  builder_.add_pos(pos);
  builder_.add_player_id(player_id);
  return builder_.Finish();
}

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA_TYPE = 4,
    VT_DATA = 6
  };
  Protocol::PacketData data_type() const {
    return static_cast<Protocol::PacketData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const Protocol::C_Move *data_as_C_Move() const {
    return data_type() == Protocol::PacketData_C_Move ? static_cast<const Protocol::C_Move *>(data()) : nullptr;
  }
  const Protocol::S_Move *data_as_S_Move() const {
    return data_type() == Protocol::PacketData_S_Move ? static_cast<const Protocol::S_Move *>(data()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyPacketData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Protocol::C_Move *Packet::data_as<Protocol::C_Move>() const {
  return data_as_C_Move();
}

template<> inline const Protocol::S_Move *Packet::data_as<Protocol::S_Move>() const {
  return data_as_S_Move();
}

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data_type(Protocol::PacketData data_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(Packet::VT_DATA, data);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Protocol::PacketData data_type = Protocol::PacketData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline bool VerifyPacketData(::flatbuffers::Verifier &verifier, const void *obj, PacketData type) {
  switch (type) {
    case PacketData_NONE: {
      return true;
    }
    case PacketData_C_Move: {
      auto ptr = reinterpret_cast<const Protocol::C_Move *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PacketData_S_Move: {
      auto ptr = reinterpret_cast<const Protocol::S_Move *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPacketDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketData(
        verifier,  values->Get(i), types->GetEnum<PacketData>(i))) {
      return false;
    }
  }
  return true;
}

inline const Protocol::Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<Protocol::Packet>(buf);
}

inline const Protocol::Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Protocol::Packet>(buf);
}

inline bool VerifyPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Protocol::Packet>(nullptr);
}

inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Protocol::Packet>(nullptr);
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Protocol::Packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Protocol::Packet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_PROTOCOL_PROTOCOL_H_
