// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 5.29.3

#ifndef Protocol_2eproto_2epb_2eh
#define Protocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Protocol_2eproto;
namespace Protocol {
class C_Chat;
struct C_ChatDefaultTypeInternal;
extern C_ChatDefaultTypeInternal _C_Chat_default_instance_;
class C_LoginReq;
struct C_LoginReqDefaultTypeInternal;
extern C_LoginReqDefaultTypeInternal _C_LoginReq_default_instance_;
class PlayerInfo;
struct PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
class S_Chat;
struct S_ChatDefaultTypeInternal;
extern S_ChatDefaultTypeInternal _S_Chat_default_instance_;
class S_LoginRes;
struct S_LoginResDefaultTypeInternal;
extern S_LoginResDefaultTypeInternal _S_LoginRes_default_instance_;
class S_OnPlayerJoined;
struct S_OnPlayerJoinedDefaultTypeInternal;
extern S_OnPlayerJoinedDefaultTypeInternal _S_OnPlayerJoined_default_instance_;
class S_OnPlayerLeft;
struct S_OnPlayerLeftDefaultTypeInternal;
extern S_OnPlayerLeftDefaultTypeInternal _S_OnPlayerLeft_default_instance_;
class S_TransferReq;
struct S_TransferReqDefaultTypeInternal;
extern S_TransferReqDefaultTypeInternal _S_TransferReq_default_instance_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum MsgId : int {
  Id_None = 0,
  Id_C_LoginReq = 101,
  Id_S_LoginRes = 102,
  Id_S_TransferReq = 103,
  Id_S_OnPlayerJoined = 104,
  Id_S_OnPlayerLeft = 105,
  Id_C_Chat = 301,
  Id_S_Chat = 302,
  Id_C_Move = 201,
  Id_S_Move = 202,
  MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool MsgId_IsValid(int value);
extern const uint32_t MsgId_internal_data_[];
constexpr MsgId MsgId_MIN = static_cast<MsgId>(0);
constexpr MsgId MsgId_MAX = static_cast<MsgId>(302);
constexpr int MsgId_ARRAYSIZE = 302 + 1;
const ::google::protobuf::EnumDescriptor*
MsgId_descriptor();
template <typename T>
const std::string& MsgId_Name(T value) {
  static_assert(std::is_same<T, MsgId>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MsgId_Name().");
  return ::google::protobuf::internal::NameOfEnum(MsgId_descriptor(), value);
}
inline bool MsgId_Parse(absl::string_view name, MsgId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgId>(
      MsgId_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class S_TransferReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_TransferReq) */ {
 public:
  inline S_TransferReq() : S_TransferReq(nullptr) {}
  ~S_TransferReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_TransferReq* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_TransferReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_TransferReq(
      ::google::protobuf::internal::ConstantInitialized);

  inline S_TransferReq(const S_TransferReq& from) : S_TransferReq(nullptr, from) {}
  inline S_TransferReq(S_TransferReq&& from) noexcept
      : S_TransferReq(nullptr, std::move(from)) {}
  inline S_TransferReq& operator=(const S_TransferReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_TransferReq& operator=(S_TransferReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_TransferReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_TransferReq* internal_default_instance() {
    return reinterpret_cast<const S_TransferReq*>(
        &_S_TransferReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(S_TransferReq& a, S_TransferReq& b) { a.Swap(&b); }
  inline void Swap(S_TransferReq* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_TransferReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_TransferReq* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_TransferReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_TransferReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_TransferReq& from) { S_TransferReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_TransferReq* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_TransferReq"; }

 protected:
  explicit S_TransferReq(::google::protobuf::Arena* arena);
  S_TransferReq(::google::protobuf::Arena* arena, const S_TransferReq& from);
  S_TransferReq(::google::protobuf::Arena* arena, S_TransferReq&& from) noexcept
      : S_TransferReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTargetIpFieldNumber = 1,
    kTransferTokenFieldNumber = 3,
    kTargetPortFieldNumber = 2,
  };
  // string TargetIp = 1;
  void clear_targetip() ;
  const std::string& targetip() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_targetip(Arg_&& arg, Args_... args);
  std::string* mutable_targetip();
  PROTOBUF_NODISCARD std::string* release_targetip();
  void set_allocated_targetip(std::string* value);

  private:
  const std::string& _internal_targetip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetip(
      const std::string& value);
  std::string* _internal_mutable_targetip();

  public:
  // string TransferToken = 3;
  void clear_transfertoken() ;
  const std::string& transfertoken() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_transfertoken(Arg_&& arg, Args_... args);
  std::string* mutable_transfertoken();
  PROTOBUF_NODISCARD std::string* release_transfertoken();
  void set_allocated_transfertoken(std::string* value);

  private:
  const std::string& _internal_transfertoken() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_transfertoken(
      const std::string& value);
  std::string* _internal_mutable_transfertoken();

  public:
  // int32 TargetPort = 2;
  void clear_targetport() ;
  ::int32_t targetport() const;
  void set_targetport(::int32_t value);

  private:
  ::int32_t _internal_targetport() const;
  void _internal_set_targetport(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_TransferReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      52, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S_TransferReq& from_msg);
    ::google::protobuf::internal::ArenaStringPtr targetip_;
    ::google::protobuf::internal::ArenaStringPtr transfertoken_;
    ::int32_t targetport_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_OnPlayerLeft final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_OnPlayerLeft) */ {
 public:
  inline S_OnPlayerLeft() : S_OnPlayerLeft(nullptr) {}
  ~S_OnPlayerLeft() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_OnPlayerLeft* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_OnPlayerLeft));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_OnPlayerLeft(
      ::google::protobuf::internal::ConstantInitialized);

  inline S_OnPlayerLeft(const S_OnPlayerLeft& from) : S_OnPlayerLeft(nullptr, from) {}
  inline S_OnPlayerLeft(S_OnPlayerLeft&& from) noexcept
      : S_OnPlayerLeft(nullptr, std::move(from)) {}
  inline S_OnPlayerLeft& operator=(const S_OnPlayerLeft& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_OnPlayerLeft& operator=(S_OnPlayerLeft&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_OnPlayerLeft& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_OnPlayerLeft* internal_default_instance() {
    return reinterpret_cast<const S_OnPlayerLeft*>(
        &_S_OnPlayerLeft_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(S_OnPlayerLeft& a, S_OnPlayerLeft& b) { a.Swap(&b); }
  inline void Swap(S_OnPlayerLeft* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_OnPlayerLeft* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_OnPlayerLeft* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_OnPlayerLeft>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_OnPlayerLeft& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_OnPlayerLeft& from) { S_OnPlayerLeft::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_OnPlayerLeft* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_OnPlayerLeft"; }

 protected:
  explicit S_OnPlayerLeft(::google::protobuf::Arena* arena);
  S_OnPlayerLeft(::google::protobuf::Arena* arena, const S_OnPlayerLeft& from);
  S_OnPlayerLeft(::google::protobuf::Arena* arena, S_OnPlayerLeft&& from) noexcept
      : S_OnPlayerLeft(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerIdFieldNumber = 1,
  };
  // int32 PlayerId = 1;
  void clear_playerid() ;
  ::int32_t playerid() const;
  void set_playerid(::int32_t value);

  private:
  ::int32_t _internal_playerid() const;
  void _internal_set_playerid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_OnPlayerLeft)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S_OnPlayerLeft& from_msg);
    ::int32_t playerid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_Chat final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_Chat) */ {
 public:
  inline S_Chat() : S_Chat(nullptr) {}
  ~S_Chat() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_Chat* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_Chat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_Chat(
      ::google::protobuf::internal::ConstantInitialized);

  inline S_Chat(const S_Chat& from) : S_Chat(nullptr, from) {}
  inline S_Chat(S_Chat&& from) noexcept
      : S_Chat(nullptr, std::move(from)) {}
  inline S_Chat& operator=(const S_Chat& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_Chat& operator=(S_Chat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_Chat& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_Chat* internal_default_instance() {
    return reinterpret_cast<const S_Chat*>(
        &_S_Chat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(S_Chat& a, S_Chat& b) { a.Swap(&b); }
  inline void Swap(S_Chat* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_Chat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_Chat* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_Chat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_Chat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_Chat& from) { S_Chat::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_Chat* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_Chat"; }

 protected:
  explicit S_Chat(::google::protobuf::Arena* arena);
  S_Chat(::google::protobuf::Arena* arena, const S_Chat& from);
  S_Chat(::google::protobuf::Arena* arena, S_Chat&& from) noexcept
      : S_Chat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgFieldNumber = 2,
    kPlayerIdFieldNumber = 1,
  };
  // string Msg = 2;
  void clear_msg() ;
  const std::string& msg() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* value);

  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(
      const std::string& value);
  std::string* _internal_mutable_msg();

  public:
  // int32 PlayerId = 1;
  void clear_playerid() ;
  ::int32_t playerid() const;
  void set_playerid(::int32_t value);

  private:
  ::int32_t _internal_playerid() const;
  void _internal_set_playerid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_Chat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      27, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S_Chat& from_msg);
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::int32_t playerid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class PlayerInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.PlayerInfo) */ {
 public:
  inline PlayerInfo() : PlayerInfo(nullptr) {}
  ~PlayerInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlayerInfo* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlayerInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlayerInfo(
      ::google::protobuf::internal::ConstantInitialized);

  inline PlayerInfo(const PlayerInfo& from) : PlayerInfo(nullptr, from) {}
  inline PlayerInfo(PlayerInfo&& from) noexcept
      : PlayerInfo(nullptr, std::move(from)) {}
  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerInfo& operator=(PlayerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerInfo*>(
        &_PlayerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PlayerInfo& a, PlayerInfo& b) { a.Swap(&b); }
  inline void Swap(PlayerInfo* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerInfo* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlayerInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlayerInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlayerInfo& from) { PlayerInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlayerInfo* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.PlayerInfo"; }

 protected:
  explicit PlayerInfo(::google::protobuf::Arena* arena);
  PlayerInfo(::google::protobuf::Arena* arena, const PlayerInfo& from);
  PlayerInfo(::google::protobuf::Arena* arena, PlayerInfo&& from) noexcept
      : PlayerInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerIdFieldNumber = 1,
    kPosXFieldNumber = 2,
    kPosYFieldNumber = 3,
    kPosZFieldNumber = 4,
  };
  // int32 PlayerId = 1;
  void clear_playerid() ;
  ::int32_t playerid() const;
  void set_playerid(::int32_t value);

  private:
  ::int32_t _internal_playerid() const;
  void _internal_set_playerid(::int32_t value);

  public:
  // float PosX = 2;
  void clear_posx() ;
  float posx() const;
  void set_posx(float value);

  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);

  public:
  // float PosY = 3;
  void clear_posy() ;
  float posy() const;
  void set_posy(float value);

  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);

  public:
  // float PosZ = 4;
  void clear_posz() ;
  float posz() const;
  void set_posz(float value);

  private:
  float _internal_posz() const;
  void _internal_set_posz(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.PlayerInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PlayerInfo& from_msg);
    ::int32_t playerid_;
    float posx_;
    float posy_;
    float posz_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_LoginReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_LoginReq) */ {
 public:
  inline C_LoginReq() : C_LoginReq(nullptr) {}
  ~C_LoginReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_LoginReq* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_LoginReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_LoginReq(
      ::google::protobuf::internal::ConstantInitialized);

  inline C_LoginReq(const C_LoginReq& from) : C_LoginReq(nullptr, from) {}
  inline C_LoginReq(C_LoginReq&& from) noexcept
      : C_LoginReq(nullptr, std::move(from)) {}
  inline C_LoginReq& operator=(const C_LoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LoginReq& operator=(C_LoginReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LoginReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_LoginReq* internal_default_instance() {
    return reinterpret_cast<const C_LoginReq*>(
        &_C_LoginReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(C_LoginReq& a, C_LoginReq& b) { a.Swap(&b); }
  inline void Swap(C_LoginReq* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LoginReq* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_LoginReq* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_LoginReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_LoginReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_LoginReq& from) { C_LoginReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_LoginReq* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_LoginReq"; }

 protected:
  explicit C_LoginReq(::google::protobuf::Arena* arena);
  C_LoginReq(::google::protobuf::Arena* arena, const C_LoginReq& from);
  C_LoginReq(::google::protobuf::Arena* arena, C_LoginReq&& from) noexcept
      : C_LoginReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAuthTokenFieldNumber = 1,
    kTransferTokenFieldNumber = 2,
  };
  // string AuthToken = 1;
  void clear_authtoken() ;
  const std::string& authtoken() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_authtoken(Arg_&& arg, Args_... args);
  std::string* mutable_authtoken();
  PROTOBUF_NODISCARD std::string* release_authtoken();
  void set_allocated_authtoken(std::string* value);

  private:
  const std::string& _internal_authtoken() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_authtoken(
      const std::string& value);
  std::string* _internal_mutable_authtoken();

  public:
  // string TransferToken = 2;
  void clear_transfertoken() ;
  const std::string& transfertoken() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_transfertoken(Arg_&& arg, Args_... args);
  std::string* mutable_transfertoken();
  PROTOBUF_NODISCARD std::string* release_transfertoken();
  void set_allocated_transfertoken(std::string* value);

  private:
  const std::string& _internal_transfertoken() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_transfertoken(
      const std::string& value);
  std::string* _internal_mutable_transfertoken();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_LoginReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      50, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const C_LoginReq& from_msg);
    ::google::protobuf::internal::ArenaStringPtr authtoken_;
    ::google::protobuf::internal::ArenaStringPtr transfertoken_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_Chat final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_Chat) */ {
 public:
  inline C_Chat() : C_Chat(nullptr) {}
  ~C_Chat() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_Chat* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_Chat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_Chat(
      ::google::protobuf::internal::ConstantInitialized);

  inline C_Chat(const C_Chat& from) : C_Chat(nullptr, from) {}
  inline C_Chat(C_Chat&& from) noexcept
      : C_Chat(nullptr, std::move(from)) {}
  inline C_Chat& operator=(const C_Chat& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Chat& operator=(C_Chat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Chat& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_Chat* internal_default_instance() {
    return reinterpret_cast<const C_Chat*>(
        &_C_Chat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(C_Chat& a, C_Chat& b) { a.Swap(&b); }
  inline void Swap(C_Chat* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Chat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Chat* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_Chat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_Chat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_Chat& from) { C_Chat::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_Chat* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_Chat"; }

 protected:
  explicit C_Chat(::google::protobuf::Arena* arena);
  C_Chat(::google::protobuf::Arena* arena, const C_Chat& from);
  C_Chat(::google::protobuf::Arena* arena, C_Chat&& from) noexcept
      : C_Chat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgFieldNumber = 1,
  };
  // string Msg = 1;
  void clear_msg() ;
  const std::string& msg() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* value);

  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(
      const std::string& value);
  std::string* _internal_mutable_msg();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_Chat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      27, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const C_Chat& from_msg);
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_OnPlayerJoined final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_OnPlayerJoined) */ {
 public:
  inline S_OnPlayerJoined() : S_OnPlayerJoined(nullptr) {}
  ~S_OnPlayerJoined() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_OnPlayerJoined* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_OnPlayerJoined));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_OnPlayerJoined(
      ::google::protobuf::internal::ConstantInitialized);

  inline S_OnPlayerJoined(const S_OnPlayerJoined& from) : S_OnPlayerJoined(nullptr, from) {}
  inline S_OnPlayerJoined(S_OnPlayerJoined&& from) noexcept
      : S_OnPlayerJoined(nullptr, std::move(from)) {}
  inline S_OnPlayerJoined& operator=(const S_OnPlayerJoined& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_OnPlayerJoined& operator=(S_OnPlayerJoined&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_OnPlayerJoined& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_OnPlayerJoined* internal_default_instance() {
    return reinterpret_cast<const S_OnPlayerJoined*>(
        &_S_OnPlayerJoined_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(S_OnPlayerJoined& a, S_OnPlayerJoined& b) { a.Swap(&b); }
  inline void Swap(S_OnPlayerJoined* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_OnPlayerJoined* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_OnPlayerJoined* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_OnPlayerJoined>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_OnPlayerJoined& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_OnPlayerJoined& from) { S_OnPlayerJoined::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_OnPlayerJoined* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_OnPlayerJoined"; }

 protected:
  explicit S_OnPlayerJoined(::google::protobuf::Arena* arena);
  S_OnPlayerJoined(::google::protobuf::Arena* arena, const S_OnPlayerJoined& from);
  S_OnPlayerJoined(::google::protobuf::Arena* arena, S_OnPlayerJoined&& from) noexcept
      : S_OnPlayerJoined(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerInfoFieldNumber = 1,
  };
  // .Protocol.PlayerInfo PlayerInfo = 1;
  bool has_playerinfo() const;
  void clear_playerinfo() ;
  const ::Protocol::PlayerInfo& playerinfo() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerInfo* release_playerinfo();
  ::Protocol::PlayerInfo* mutable_playerinfo();
  void set_allocated_playerinfo(::Protocol::PlayerInfo* value);
  void unsafe_arena_set_allocated_playerinfo(::Protocol::PlayerInfo* value);
  ::Protocol::PlayerInfo* unsafe_arena_release_playerinfo();

  private:
  const ::Protocol::PlayerInfo& _internal_playerinfo() const;
  ::Protocol::PlayerInfo* _internal_mutable_playerinfo();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_OnPlayerJoined)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S_OnPlayerJoined& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Protocol::PlayerInfo* playerinfo_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_LoginRes final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_LoginRes) */ {
 public:
  inline S_LoginRes() : S_LoginRes(nullptr) {}
  ~S_LoginRes() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_LoginRes* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_LoginRes));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_LoginRes(
      ::google::protobuf::internal::ConstantInitialized);

  inline S_LoginRes(const S_LoginRes& from) : S_LoginRes(nullptr, from) {}
  inline S_LoginRes(S_LoginRes&& from) noexcept
      : S_LoginRes(nullptr, std::move(from)) {}
  inline S_LoginRes& operator=(const S_LoginRes& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LoginRes& operator=(S_LoginRes&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LoginRes& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_LoginRes* internal_default_instance() {
    return reinterpret_cast<const S_LoginRes*>(
        &_S_LoginRes_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(S_LoginRes& a, S_LoginRes& b) { a.Swap(&b); }
  inline void Swap(S_LoginRes* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LoginRes* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_LoginRes* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_LoginRes>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_LoginRes& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_LoginRes& from) { S_LoginRes::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_LoginRes* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_LoginRes"; }

 protected:
  explicit S_LoginRes(::google::protobuf::Arena* arena);
  S_LoginRes(::google::protobuf::Arena* arena, const S_LoginRes& from);
  S_LoginRes(::google::protobuf::Arena* arena, S_LoginRes&& from) noexcept
      : S_LoginRes(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOtherPlayerInfosFieldNumber = 6,
    kSuccessFieldNumber = 1,
    kMySessionIdFieldNumber = 2,
    kSpawnPosXFieldNumber = 3,
    kSpawnPosYFieldNumber = 4,
    kSpawnPosZFieldNumber = 5,
  };
  // repeated .Protocol.PlayerInfo OtherPlayerInfos = 6;
  int otherplayerinfos_size() const;
  private:
  int _internal_otherplayerinfos_size() const;

  public:
  void clear_otherplayerinfos() ;
  ::Protocol::PlayerInfo* mutable_otherplayerinfos(int index);
  ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>* mutable_otherplayerinfos();

  private:
  const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>& _internal_otherplayerinfos() const;
  ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>* _internal_mutable_otherplayerinfos();
  public:
  const ::Protocol::PlayerInfo& otherplayerinfos(int index) const;
  ::Protocol::PlayerInfo* add_otherplayerinfos();
  const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>& otherplayerinfos() const;
  // bool Success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // int32 MySessionId = 2;
  void clear_mysessionid() ;
  ::int32_t mysessionid() const;
  void set_mysessionid(::int32_t value);

  private:
  ::int32_t _internal_mysessionid() const;
  void _internal_set_mysessionid(::int32_t value);

  public:
  // float SpawnPosX = 3;
  void clear_spawnposx() ;
  float spawnposx() const;
  void set_spawnposx(float value);

  private:
  float _internal_spawnposx() const;
  void _internal_set_spawnposx(float value);

  public:
  // float SpawnPosY = 4;
  void clear_spawnposy() ;
  float spawnposy() const;
  void set_spawnposy(float value);

  private:
  float _internal_spawnposy() const;
  void _internal_set_spawnposy(float value);

  public:
  // float SpawnPosZ = 5;
  void clear_spawnposz() ;
  float spawnposz() const;
  void set_spawnposz(float value);

  private:
  float _internal_spawnposz() const;
  void _internal_set_spawnposz(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_LoginRes)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const S_LoginRes& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Protocol::PlayerInfo > otherplayerinfos_;
    bool success_;
    ::int32_t mysessionid_;
    float spawnposx_;
    float spawnposy_;
    float spawnposz_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PlayerInfo

// int32 PlayerId = 1;
inline void PlayerInfo::clear_playerid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = 0;
}
inline ::int32_t PlayerInfo::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.PlayerId)
  return _internal_playerid();
}
inline void PlayerInfo::set_playerid(::int32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.PlayerId)
}
inline ::int32_t PlayerInfo::_internal_playerid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.playerid_;
}
inline void PlayerInfo::_internal_set_playerid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = value;
}

// float PosX = 2;
inline void PlayerInfo::clear_posx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posx_ = 0;
}
inline float PlayerInfo::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.PosX)
  return _internal_posx();
}
inline void PlayerInfo::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.PosX)
}
inline float PlayerInfo::_internal_posx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.posx_;
}
inline void PlayerInfo::_internal_set_posx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posx_ = value;
}

// float PosY = 3;
inline void PlayerInfo::clear_posy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posy_ = 0;
}
inline float PlayerInfo::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.PosY)
  return _internal_posy();
}
inline void PlayerInfo::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.PosY)
}
inline float PlayerInfo::_internal_posy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.posy_;
}
inline void PlayerInfo::_internal_set_posy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posy_ = value;
}

// float PosZ = 4;
inline void PlayerInfo::clear_posz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posz_ = 0;
}
inline float PlayerInfo::posz() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.PosZ)
  return _internal_posz();
}
inline void PlayerInfo::set_posz(float value) {
  _internal_set_posz(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.PosZ)
}
inline float PlayerInfo::_internal_posz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.posz_;
}
inline void PlayerInfo::_internal_set_posz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posz_ = value;
}

// -------------------------------------------------------------------

// C_LoginReq

// string AuthToken = 1;
inline void C_LoginReq::clear_authtoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authtoken_.ClearToEmpty();
}
inline const std::string& C_LoginReq::authtoken() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_LoginReq.AuthToken)
  return _internal_authtoken();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void C_LoginReq::set_authtoken(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authtoken_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_LoginReq.AuthToken)
}
inline std::string* C_LoginReq::mutable_authtoken() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_authtoken();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LoginReq.AuthToken)
  return _s;
}
inline const std::string& C_LoginReq::_internal_authtoken() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.authtoken_.Get();
}
inline void C_LoginReq::_internal_set_authtoken(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authtoken_.Set(value, GetArena());
}
inline std::string* C_LoginReq::_internal_mutable_authtoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.authtoken_.Mutable( GetArena());
}
inline std::string* C_LoginReq::release_authtoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_LoginReq.AuthToken)
  return _impl_.authtoken_.Release();
}
inline void C_LoginReq::set_allocated_authtoken(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.authtoken_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.authtoken_.IsDefault()) {
    _impl_.authtoken_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LoginReq.AuthToken)
}

// string TransferToken = 2;
inline void C_LoginReq::clear_transfertoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.ClearToEmpty();
}
inline const std::string& C_LoginReq::transfertoken() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_LoginReq.TransferToken)
  return _internal_transfertoken();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void C_LoginReq::set_transfertoken(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_LoginReq.TransferToken)
}
inline std::string* C_LoginReq::mutable_transfertoken() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_transfertoken();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LoginReq.TransferToken)
  return _s;
}
inline const std::string& C_LoginReq::_internal_transfertoken() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.transfertoken_.Get();
}
inline void C_LoginReq::_internal_set_transfertoken(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.Set(value, GetArena());
}
inline std::string* C_LoginReq::_internal_mutable_transfertoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.transfertoken_.Mutable( GetArena());
}
inline std::string* C_LoginReq::release_transfertoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_LoginReq.TransferToken)
  return _impl_.transfertoken_.Release();
}
inline void C_LoginReq::set_allocated_transfertoken(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.transfertoken_.IsDefault()) {
    _impl_.transfertoken_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LoginReq.TransferToken)
}

// -------------------------------------------------------------------

// S_LoginRes

// bool Success = 1;
inline void S_LoginRes::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool S_LoginRes::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginRes.Success)
  return _internal_success();
}
inline void S_LoginRes::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginRes.Success)
}
inline bool S_LoginRes::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void S_LoginRes::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// int32 MySessionId = 2;
inline void S_LoginRes::clear_mysessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mysessionid_ = 0;
}
inline ::int32_t S_LoginRes::mysessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginRes.MySessionId)
  return _internal_mysessionid();
}
inline void S_LoginRes::set_mysessionid(::int32_t value) {
  _internal_set_mysessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginRes.MySessionId)
}
inline ::int32_t S_LoginRes::_internal_mysessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mysessionid_;
}
inline void S_LoginRes::_internal_set_mysessionid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mysessionid_ = value;
}

// float SpawnPosX = 3;
inline void S_LoginRes::clear_spawnposx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spawnposx_ = 0;
}
inline float S_LoginRes::spawnposx() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginRes.SpawnPosX)
  return _internal_spawnposx();
}
inline void S_LoginRes::set_spawnposx(float value) {
  _internal_set_spawnposx(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginRes.SpawnPosX)
}
inline float S_LoginRes::_internal_spawnposx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spawnposx_;
}
inline void S_LoginRes::_internal_set_spawnposx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spawnposx_ = value;
}

// float SpawnPosY = 4;
inline void S_LoginRes::clear_spawnposy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spawnposy_ = 0;
}
inline float S_LoginRes::spawnposy() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginRes.SpawnPosY)
  return _internal_spawnposy();
}
inline void S_LoginRes::set_spawnposy(float value) {
  _internal_set_spawnposy(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginRes.SpawnPosY)
}
inline float S_LoginRes::_internal_spawnposy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spawnposy_;
}
inline void S_LoginRes::_internal_set_spawnposy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spawnposy_ = value;
}

// float SpawnPosZ = 5;
inline void S_LoginRes::clear_spawnposz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spawnposz_ = 0;
}
inline float S_LoginRes::spawnposz() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginRes.SpawnPosZ)
  return _internal_spawnposz();
}
inline void S_LoginRes::set_spawnposz(float value) {
  _internal_set_spawnposz(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginRes.SpawnPosZ)
}
inline float S_LoginRes::_internal_spawnposz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spawnposz_;
}
inline void S_LoginRes::_internal_set_spawnposz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spawnposz_ = value;
}

// repeated .Protocol.PlayerInfo OtherPlayerInfos = 6;
inline int S_LoginRes::_internal_otherplayerinfos_size() const {
  return _internal_otherplayerinfos().size();
}
inline int S_LoginRes::otherplayerinfos_size() const {
  return _internal_otherplayerinfos_size();
}
inline void S_LoginRes::clear_otherplayerinfos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherplayerinfos_.Clear();
}
inline ::Protocol::PlayerInfo* S_LoginRes::mutable_otherplayerinfos(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Protocol.S_LoginRes.OtherPlayerInfos)
  return _internal_mutable_otherplayerinfos()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>* S_LoginRes::mutable_otherplayerinfos()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_LoginRes.OtherPlayerInfos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_otherplayerinfos();
}
inline const ::Protocol::PlayerInfo& S_LoginRes::otherplayerinfos(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginRes.OtherPlayerInfos)
  return _internal_otherplayerinfos().Get(index);
}
inline ::Protocol::PlayerInfo* S_LoginRes::add_otherplayerinfos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Protocol::PlayerInfo* _add = _internal_mutable_otherplayerinfos()->Add();
  // @@protoc_insertion_point(field_add:Protocol.S_LoginRes.OtherPlayerInfos)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>& S_LoginRes::otherplayerinfos() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Protocol.S_LoginRes.OtherPlayerInfos)
  return _internal_otherplayerinfos();
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>&
S_LoginRes::_internal_otherplayerinfos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.otherplayerinfos_;
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::PlayerInfo>*
S_LoginRes::_internal_mutable_otherplayerinfos() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.otherplayerinfos_;
}

// -------------------------------------------------------------------

// S_TransferReq

// string TargetIp = 1;
inline void S_TransferReq::clear_targetip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetip_.ClearToEmpty();
}
inline const std::string& S_TransferReq::targetip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_TransferReq.TargetIp)
  return _internal_targetip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void S_TransferReq::set_targetip(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_TransferReq.TargetIp)
}
inline std::string* S_TransferReq::mutable_targetip() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_targetip();
  // @@protoc_insertion_point(field_mutable:Protocol.S_TransferReq.TargetIp)
  return _s;
}
inline const std::string& S_TransferReq::_internal_targetip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.targetip_.Get();
}
inline void S_TransferReq::_internal_set_targetip(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetip_.Set(value, GetArena());
}
inline std::string* S_TransferReq::_internal_mutable_targetip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.targetip_.Mutable( GetArena());
}
inline std::string* S_TransferReq::release_targetip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_TransferReq.TargetIp)
  return _impl_.targetip_.Release();
}
inline void S_TransferReq::set_allocated_targetip(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.targetip_.IsDefault()) {
    _impl_.targetip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_TransferReq.TargetIp)
}

// int32 TargetPort = 2;
inline void S_TransferReq::clear_targetport() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetport_ = 0;
}
inline ::int32_t S_TransferReq::targetport() const {
  // @@protoc_insertion_point(field_get:Protocol.S_TransferReq.TargetPort)
  return _internal_targetport();
}
inline void S_TransferReq::set_targetport(::int32_t value) {
  _internal_set_targetport(value);
  // @@protoc_insertion_point(field_set:Protocol.S_TransferReq.TargetPort)
}
inline ::int32_t S_TransferReq::_internal_targetport() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.targetport_;
}
inline void S_TransferReq::_internal_set_targetport(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetport_ = value;
}

// string TransferToken = 3;
inline void S_TransferReq::clear_transfertoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.ClearToEmpty();
}
inline const std::string& S_TransferReq::transfertoken() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_TransferReq.TransferToken)
  return _internal_transfertoken();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void S_TransferReq::set_transfertoken(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_TransferReq.TransferToken)
}
inline std::string* S_TransferReq::mutable_transfertoken() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_transfertoken();
  // @@protoc_insertion_point(field_mutable:Protocol.S_TransferReq.TransferToken)
  return _s;
}
inline const std::string& S_TransferReq::_internal_transfertoken() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.transfertoken_.Get();
}
inline void S_TransferReq::_internal_set_transfertoken(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.Set(value, GetArena());
}
inline std::string* S_TransferReq::_internal_mutable_transfertoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.transfertoken_.Mutable( GetArena());
}
inline std::string* S_TransferReq::release_transfertoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_TransferReq.TransferToken)
  return _impl_.transfertoken_.Release();
}
inline void S_TransferReq::set_allocated_transfertoken(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transfertoken_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.transfertoken_.IsDefault()) {
    _impl_.transfertoken_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_TransferReq.TransferToken)
}

// -------------------------------------------------------------------

// S_OnPlayerJoined

// .Protocol.PlayerInfo PlayerInfo = 1;
inline bool S_OnPlayerJoined::has_playerinfo() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.playerinfo_ != nullptr);
  return value;
}
inline void S_OnPlayerJoined::clear_playerinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.playerinfo_ != nullptr) _impl_.playerinfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Protocol::PlayerInfo& S_OnPlayerJoined::_internal_playerinfo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::PlayerInfo* p = _impl_.playerinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerInfo&>(::Protocol::_PlayerInfo_default_instance_);
}
inline const ::Protocol::PlayerInfo& S_OnPlayerJoined::playerinfo() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_OnPlayerJoined.PlayerInfo)
  return _internal_playerinfo();
}
inline void S_OnPlayerJoined::unsafe_arena_set_allocated_playerinfo(::Protocol::PlayerInfo* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.playerinfo_);
  }
  _impl_.playerinfo_ = reinterpret_cast<::Protocol::PlayerInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_OnPlayerJoined.PlayerInfo)
}
inline ::Protocol::PlayerInfo* S_OnPlayerJoined::release_playerinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::PlayerInfo* released = _impl_.playerinfo_;
  _impl_.playerinfo_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::PlayerInfo* S_OnPlayerJoined::unsafe_arena_release_playerinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_OnPlayerJoined.PlayerInfo)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::PlayerInfo* temp = _impl_.playerinfo_;
  _impl_.playerinfo_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerInfo* S_OnPlayerJoined::_internal_mutable_playerinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.playerinfo_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::PlayerInfo>(GetArena());
    _impl_.playerinfo_ = reinterpret_cast<::Protocol::PlayerInfo*>(p);
  }
  return _impl_.playerinfo_;
}
inline ::Protocol::PlayerInfo* S_OnPlayerJoined::mutable_playerinfo() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Protocol::PlayerInfo* _msg = _internal_mutable_playerinfo();
  // @@protoc_insertion_point(field_mutable:Protocol.S_OnPlayerJoined.PlayerInfo)
  return _msg;
}
inline void S_OnPlayerJoined::set_allocated_playerinfo(::Protocol::PlayerInfo* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.playerinfo_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.playerinfo_ = reinterpret_cast<::Protocol::PlayerInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_OnPlayerJoined.PlayerInfo)
}

// -------------------------------------------------------------------

// S_OnPlayerLeft

// int32 PlayerId = 1;
inline void S_OnPlayerLeft::clear_playerid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = 0;
}
inline ::int32_t S_OnPlayerLeft::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_OnPlayerLeft.PlayerId)
  return _internal_playerid();
}
inline void S_OnPlayerLeft::set_playerid(::int32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_OnPlayerLeft.PlayerId)
}
inline ::int32_t S_OnPlayerLeft::_internal_playerid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.playerid_;
}
inline void S_OnPlayerLeft::_internal_set_playerid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = value;
}

// -------------------------------------------------------------------

// C_Chat

// string Msg = 1;
inline void C_Chat::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& C_Chat::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_Chat.Msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void C_Chat::set_msg(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_Chat.Msg)
}
inline std::string* C_Chat::mutable_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:Protocol.C_Chat.Msg)
  return _s;
}
inline const std::string& C_Chat::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void C_Chat::_internal_set_msg(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(value, GetArena());
}
inline std::string* C_Chat::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msg_.Mutable( GetArena());
}
inline std::string* C_Chat::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_Chat.Msg)
  return _impl_.msg_.Release();
}
inline void C_Chat::set_allocated_msg(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_Chat.Msg)
}

// -------------------------------------------------------------------

// S_Chat

// int32 PlayerId = 1;
inline void S_Chat::clear_playerid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = 0;
}
inline ::int32_t S_Chat::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_Chat.PlayerId)
  return _internal_playerid();
}
inline void S_Chat::set_playerid(::int32_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_Chat.PlayerId)
}
inline ::int32_t S_Chat::_internal_playerid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.playerid_;
}
inline void S_Chat::_internal_set_playerid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = value;
}

// string Msg = 2;
inline void S_Chat::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& S_Chat::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_Chat.Msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void S_Chat::set_msg(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.S_Chat.Msg)
}
inline std::string* S_Chat::mutable_msg() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:Protocol.S_Chat.Msg)
  return _s;
}
inline const std::string& S_Chat::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void S_Chat::_internal_set_msg(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(value, GetArena());
}
inline std::string* S_Chat::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msg_.Mutable( GetArena());
}
inline std::string* S_Chat::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.S_Chat.Msg)
  return _impl_.msg_.Release();
}
inline void S_Chat::set_allocated_msg(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_Chat.Msg)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::MsgId> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::MsgId>() {
  return ::Protocol::MsgId_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Protocol_2eproto_2epb_2eh
